window.MOZAIKA_PEOPLES = [
  {
    slug: "nanai",
    name: "Нанайцы",
    image: "../assets/site-images-v1/people/nanai-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/nanai-320.webp 320w, ../assets/site-images-v1/people/nanai-512.webp 512w, ../assets/site-images-v1/people/nanai-768.webp 768w, ../assets/site-images-v1/people/nanai-1024.webp 1024w",
    titleMax: 118,
    population: "11 668 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Амур и его притоки",
    area: "amur",
    areaLabel: "Амур",
    language: "нанайский язык · тунгусо-маньчжурская семья",
    focus: "рыболовство, орнамент, одежда из рыбьей кожи",
    summary:
      "Нанайцы исторически связаны с Амуром и его притоками. Река определяла поселения, промысел, питание, календарь и многие ремесленные практики. В культуре особенно важны рыболовство, семейная память, орнамент и работа с рыбьей кожей.",
    lead:
      "Культура нанайцев раскрывается через реку: промысел, поселения, семейную память, орнамент и отношение к природной среде.",
    facts: ["Нижний и средний Амур", "устные предания", "рыбья кожа"],
    sections: [
      ["Территория", "Нанайские поселения в Хабаровском крае связаны с Амуром, его протоками и озерами. Важные точки памяти - Найхин, Дада, Джари, Сикачи-Алян, Ачан, Джуен и другие села амурского ареала."],
      ["Язык", "Нанайский язык относится к тунгусо-маньчжурской семье. Сегодня он требует поддержки: живое владение сильнее сохраняется у старших носителей, а школы, словари и культурные проекты становятся способом передачи языка молодежи."],
      ["Материальная культура", "Рыболовство, изготовление юколы, лодки, орнамент, халаты и обувь из природных материалов помогают увидеть, как практическое знание превращалось в художественный язык."],
    ],
    immersion: [
      {
        kicker: "река",
        title: "Амур как система жизни",
        image: "../assets/site-images-v1/immersion/nanai-amur-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nanai-amur-480.webp 480w, ../assets/site-images-v1/immersion/nanai-amur-960.webp 960w, ../assets/site-images-v1/immersion/nanai-amur-1254.webp 1254w",
        text: "Для нанайцев Амур был не только маршрутом. Он задавал сезонность, места промысла, способы хранения рыбы и структуру поселений. Поэтому разговор о культуре начинается с воды, берега и семейных историй, связанных с ними.",
        details: ["сезонный промысел", "поселения у воды", "рыба как основа питания"],
      },
      {
        kicker: "ремесло",
        title: "Рыбья кожа и орнамент",
        image: "../assets/site-images-v1/immersion/nanai-ornament-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nanai-ornament-480.webp 480w, ../assets/site-images-v1/immersion/nanai-ornament-960.webp 960w, ../assets/site-images-v1/immersion/nanai-ornament-1254.webp 1254w",
        text: "Одежда и предметы быта показывают высокий уровень ремесла: кожа, мех, ткань, бисер и вышивка соединялись с орнаментами, которые передавали представления о красоте, защите и принадлежности к роду.",
        details: ["обработка кожи", "вышивка", "родовые мотивы"],
      },
      {
        kicker: "память",
        title: "Живая передача",
        image: "../assets/site-images-v1/immersion/nanai-living-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nanai-living-480.webp 480w, ../assets/site-images-v1/immersion/nanai-living-960.webp 960w, ../assets/site-images-v1/immersion/nanai-living-1254.webp 1254w",
        text: "Современное сохранение нанайской культуры держится на языке, фольклоре, локальных музеях, ансамблях, семейных рассказах и образовательных проектах, где молодые люди встречаются с наследием напрямую.",
        details: ["фольклор", "музеи", "молодежные встречи"],
      },
    ],
    timeline: ["Амур как центр жизни", "Промысел и ремесло", "Сохранение языка и памяти"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Какая связка точнее всего отличает нанайскую тему в атласе?",
      options: ["Амур, рыболовство и работа с рыбьей кожей", "Север Камчатки, оленеводство и горная тундра", "Командорские острова, морская навигация и алеутский язык"],
      answer: "Амур, рыболовство и работа с рыбьей кожей",
    },
  },
  {
    slug: "ulchi",
    name: "Ульчи",
    image: "../assets/site-images-v1/people/ulchi-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/ulchi-320.webp 320w, ../assets/site-images-v1/people/ulchi-512.webp 512w, ../assets/site-images-v1/people/ulchi-768.webp 768w, ../assets/site-images-v1/people/ulchi-1024.webp 1024w",
    titleMax: 118,
    population: "2 481 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Нижний Амур",
    area: "amur",
    areaLabel: "Амур",
    language: "ульчский язык · тунгусо-маньчжурская семья",
    focus: "амурское рыболовство, лодки, оседлые поселения",
    summary:
      "Ульчи живут в нижнем течении Амура, прежде всего в Ульчском районе Хабаровского края. Их культура формировалась вокруг оседлых поселений, рыболовства, лодок, собачьих упряжек, ремесел и тесных контактов с другими народами Амура.",
    lead:
      "Ульчская культура помогает увидеть, как река становится не фоном, а системой жизни: маршрутом, промыслом и памятью рода.",
    facts: ["Ульчский район", "Нижний Амур", "рыболовство"],
    sections: [
      ["Территория", "Исторический ареал ульчей связан с нижним течением Амура. Важны поселения у воды, где промысел, транспорт и семейные связи складывались вокруг речного календаря."],
      ["Язык", "Ульчский язык входит в южную, амурскую ветвь тунгусо-маньчжурских языков. Для образовательного сайта важно показывать язык не как музейный объект, а как часть семейной и локальной памяти."],
      ["Культура", "Круглогодичное рыболовство, охота, лодки, нарты, халаты, обувь из рыбьей и звериной кожи, орнамент и фольклор образуют плотную картину амурского уклада."],
    ],
    immersion: [
      {
        kicker: "селение",
        title: "Оседлая жизнь у воды",
        image: "../assets/site-images-v1/immersion/ulchi-water-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/ulchi-water-480.webp 480w, ../assets/site-images-v1/immersion/ulchi-water-960.webp 960w, ../assets/site-images-v1/immersion/ulchi-water-1254.webp 1254w",
        text: "История ульчских поселений часто измеряется десятилетиями и столетиями. Это культура постоянного берега, где дом, лодка, промысел и соседские связи складываются в единую систему.",
        details: ["села Нижнего Амура", "дом и берег", "семейная память"],
      },
      {
        kicker: "промысел",
        title: "Рыба как календарь",
        image: "../assets/site-images-v1/immersion/ulchi-fish-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/ulchi-fish-480.webp 480w, ../assets/site-images-v1/immersion/ulchi-fish-960.webp 960w, ../assets/site-images-v1/immersion/ulchi-fish-1254.webp 1254w",
        text: "Рыболовство определяло питание, заготовки, маршруты и трудовой год. Лосось, юкола, снасти и способы хранения - не бытовые детали, а ключ к пониманию устойчивости культуры.",
        details: ["лососевые", "юкола", "сезонность"],
      },
      {
        kicker: "соседство",
        title: "Амурская общность",
        image: "../assets/site-images-v1/immersion/ulchi-amur-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/ulchi-amur-480.webp 480w, ../assets/site-images-v1/immersion/ulchi-amur-960.webp 960w, ../assets/site-images-v1/immersion/ulchi-amur-1254.webp 1254w",
        text: "Культура ульчей развивалась в тесном соседстве с нанайцами, нивхами, негидальцами и эвенками. Поэтому в ней важны не только уникальные черты, но и общий амурский культурный контекст.",
        details: ["обмен практиками", "смешанные поселения", "орнамент"],
      },
    ],
    timeline: ["Нижний Амур", "Сезонный промысел", "Передача семейной памяти"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Что точнее всего отделяет ульчскую страницу от нанайской при общей амурской среде?",
      options: ["Оседлые поселения Нижнего Амура и ульчский районный контекст", "Арктическое побережье и юпикская языковая традиция", "Островной уклад Командор и алеутский язык"],
      answer: "Оседлые поселения Нижнего Амура и ульчский районный контекст",
    },
  },
  {
    slug: "nivkh",
    name: "Нивхи",
    image: "../assets/site-images-v1/people/nivkh-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/nivkh-320.webp 320w, ../assets/site-images-v1/people/nivkh-512.webp 512w, ../assets/site-images-v1/people/nivkh-768.webp 768w, ../assets/site-images-v1/people/nivkh-1024.webp 1024w",
    titleMax: 118,
    population: "3 863 человека в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Амурский лиман и Сахалин",
    area: "coast",
    areaLabel: "Побережье",
    language: "нивхский язык · язык-изолят",
    focus: "рыболовство, морской промысел, обрядовая культура",
    summary:
      "Нивхи связаны с низовьями Амура, Амурским лиманом, побережьем Охотского моря, Татарским проливом и Сахалином. Их культура соединяет речную и морскую среду, рыболовство, промысел морского зверя, родовую память и самостоятельный язык.",
    lead:
      "Нивхская тема соединяет Амур, лиман и море. Здесь особенно важно говорить точно: язык, обряды и родовая память имеют самостоятельную ценность.",
    facts: ["Амурский лиман", "морская среда", "самобытный язык"],
    sections: [
      ["Территория", "Материковые группы нивхов связаны с низовьями Амура, лиманом, побережьем Охотского моря и Татарского пролива; островные группы - с севером Сахалина."],
      ["Язык", "Нивхский язык обычно рассматривается как изолированный. Это делает его особенно ценным для лингвистики и одновременно уязвимым: передача языка зависит от семей, школ и культурных инициатив."],
      ["Культура", "Рыба, морской зверь, собаки, зимняя одежда, орнамент, родовые истории и обрядовые практики помогают понять культуру, в которой море и река постоянно связаны."],
    ],
    immersion: [
      {
        kicker: "граница воды",
        title: "Река встречает море",
        image: "../assets/site-images-v1/immersion/nivkh-water-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nivkh-water-480.webp 480w, ../assets/site-images-v1/immersion/nivkh-water-960.webp 960w, ../assets/site-images-v1/immersion/nivkh-water-1254.webp 1254w",
        text: "Нивхская культура раскрывается на границе Амура и морского побережья. Лиман, пролив и островные маршруты задавали промысел, питание и представления о пространстве.",
        details: ["низовья Амура", "Сахалин", "Татарский пролив"],
      },
      {
        kicker: "язык",
        title: "Самостоятельная языковая линия",
        image: "../assets/site-images-v1/immersion/nivkh-shore-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nivkh-shore-480.webp 480w, ../assets/site-images-v1/immersion/nivkh-shore-960.webp 960w, ../assets/site-images-v1/immersion/nivkh-shore-1254.webp 1254w",
        text: "Нивхский язык не сводится к языкам соседей и часто описывается как изолят. Для сайта важно подавать это как ценность, а не как сухую справку.",
        details: ["язык-изолят", "диалекты", "устная речь"],
      },
      {
        kicker: "обряд",
        title: "Память рода и промысла",
        image: "../assets/site-images-v1/immersion/nivkh-memory-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/nivkh-memory-480.webp 480w, ../assets/site-images-v1/immersion/nivkh-memory-960.webp 960w, ../assets/site-images-v1/immersion/nivkh-memory-1254.webp 1254w",
        text: "В исторической культуре важны родовые связи, промысловые знания и обрядовые формы, связанные с отношением человека к животным, воде и предкам.",
        details: ["родовые истории", "обрядовая культура", "промысловая этика"],
      },
    ],
    timeline: ["Амурский лиман", "Морской промысел", "Язык и родовая память"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Почему нивхская страница требует отдельного языкового акцента?",
      options: ["Нивхский обычно рассматривают как язык-изолят", "Нивхский входит в эскимосско-алеутскую семью", "Нивхский является диалектом корякского языка"],
      answer: "Нивхский обычно рассматривают как язык-изолят",
    },
  },
  {
    slug: "orochi",
    name: "Орочи",
    image: "../assets/site-images-v1/people/orochi-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/orochi-320.webp 320w, ../assets/site-images-v1/people/orochi-512.webp 512w, ../assets/site-images-v1/people/orochi-768.webp 768w, ../assets/site-images-v1/people/orochi-1024.webp 1024w",
    titleMax: 118,
    population: "530 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Татарский пролив и Тумнин",
    area: "coast",
    areaLabel: "Побережье",
    language: "орочский язык · тунгусо-маньчжурская семья",
    focus: "побережье, охота, рыболовство, тайга",
    summary:
      "Орочи исторически связаны с побережьем Татарского пролива, рекой Тумнин, тайгой и речными маршрутами Хабаровского края. Их уклад соединял охоту, рыболовство, морской промысел, малые стойбища и знание переходов между лесом, рекой и морем.",
    lead:
      "Культура орочей находится на пересечении побережья, тайги и рек. Это пример того, как разные природные среды образуют один уклад.",
    facts: ["Ванинский район", "побережье", "таежные маршруты"],
    sections: [
      ["Территория", "Ключевые территории связаны с низовьями Тумнина, Ванинским районом, побережьем Татарского пролива, Хунгари и частью амурского ареала."],
      ["Язык", "Орочский язык относится к тунгусо-маньчжурским языкам и находится в крайне уязвимом состоянии. Поэтому даже базовые слова, записи и учебные материалы имеют большую ценность."],
      ["Культура", "Традиционные занятия включали охоту на копытных и пушного зверя, рыболовство, морской промысел, лодки, ловушки и сезонные маршруты между берегом и тайгой."],
    ],
    immersion: [
      {
        kicker: "маршрут",
        title: "Между Тумнином и морем",
        image: "../assets/site-images-v1/immersion/orochi-route-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/orochi-route-480.webp 480w, ../assets/site-images-v1/immersion/orochi-route-960.webp 960w, ../assets/site-images-v1/immersion/orochi-route-1254.webp 1254w",
        text: "Орочская культура не укладывается в одну точку на карте: важны движение, стойбища, охотничьи тропы, реки и выход к Татарскому проливу.",
        details: ["Тумнин", "Татарский пролив", "малые стойбища"],
      },
      {
        kicker: "промысел",
        title: "Лес, река, побережье",
        image: "../assets/site-images-v1/immersion/orochi-wood-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/orochi-wood-480.webp 480w, ../assets/site-images-v1/immersion/orochi-wood-960.webp 960w, ../assets/site-images-v1/immersion/orochi-wood-1254.webp 1254w",
        text: "Охота, рыболовство и морской промысел дополняли друг друга. Такой уклад требовал точного знания поведения животных, воды, льда, погоды и сезонных перемещений.",
        details: ["охота", "рыболовство", "морской зверь"],
      },
      {
        kicker: "язык",
        title: "Хрупкая языковая память",
        image: "../assets/site-images-v1/immersion/orochi-language-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/orochi-language-480.webp 480w, ../assets/site-images-v1/immersion/orochi-language-960.webp 960w, ../assets/site-images-v1/immersion/orochi-language-1254.webp 1254w",
        text: "Орочский язык сегодня требует особого внимания. Образовательный сайт может стать местом, где видны не только факты, но и сама необходимость бережного сохранения.",
        details: ["словарные записи", "учебные материалы", "носители памяти"],
      },
    ],
    timeline: ["Побережье", "Тайга и реки", "Сохранение малочисленной культуры"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Какая формула точнее всего описывает орочский культурный маршрут?",
      options: ["Тумнин, тайга и побережье Татарского пролива", "Нижний Амур, оседлые села и ульчская языковая среда", "Сахалин, оленеводство и самоназвание ульта"],
      answer: "Тумнин, тайга и побережье Татарского пролива",
    },
  },
  {
    slug: "udege",
    name: "Удэгейцы",
    image: "../assets/site-images-v1/people/udege-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/udege-320.webp 320w, ../assets/site-images-v1/people/udege-512.webp 512w, ../assets/site-images-v1/people/udege-768.webp 768w, ../assets/site-images-v1/people/udege-1024.webp 1024w",
    titleMax: 96,
    population: "1 328 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Сихотэ-Алинь и реки",
    area: "taiga",
    areaLabel: "Тайга",
    language: "удэгейский язык · тунгусо-маньчжурская семья",
    focus: "охота, реки, дерево, береста",
    summary:
      "Удэгейцы связаны с горно-таежными территориями Сихотэ-Алиня, Приморья и юго-востока Хабаровского края. В крае важны бассейны рек Хор и Анюй, охота, рыболовство, береста, дерево, устные рассказы и экологическое знание тайги.",
    lead:
      "Удэгейская страница должна звучать как маршрут по тайге: реки, охота, береста, дерево, экологическое знание и уважение к месту.",
    facts: ["реки Хор и Анюй", "таежная культура", "ремесла"],
    sections: [
      ["Территория", "В Хабаровском крае удэгейская тема связана с бассейнами рек Хор и Анюй, а также с таежными маршрутами на стыке Хабаровского и Приморского краев."],
      ["Язык", "Удэгейский язык относится к тунгусо-маньчжурской семье. Его близость к орочскому языку и общий таежный контекст помогают увидеть связь народов региона."],
      ["Культура", "Ключевые темы - охота, рыболовство, долбленые лодки, береста, дерево, рассказы о тайге и знания о животных, растениях, погоде и маршрутах."],
    ],
    immersion: [
      {
        kicker: "тайга",
        title: "Знание леса как культура",
        image: "../assets/site-images-v1/immersion/udege-forest-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/udege-forest-480.webp 480w, ../assets/site-images-v1/immersion/udege-forest-960.webp 960w, ../assets/site-images-v1/immersion/udege-forest-1254.webp 1254w",
        text: "Удэгейское наследие невозможно отделить от тайги. Это не просто природный фон, а система ориентиров, запретов, маршрутов, промыслов и рассказов.",
        details: ["Сихотэ-Алинь", "реки", "охотничьи тропы"],
      },
      {
        kicker: "ремесло",
        title: "Дерево, береста, лодка",
        image: "../assets/site-images-v1/immersion/udege-home-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/udege-home-480.webp 480w, ../assets/site-images-v1/immersion/udege-home-960.webp 960w, ../assets/site-images-v1/immersion/udege-home-1254.webp 1254w",
        text: "Материальная культура показывает, как природные материалы становились инструментами жизни: лодками, емкостями, деталями жилища и предметами повседневного маршрута.",
        details: ["береста", "долбленые лодки", "дерево"],
      },
      {
        kicker: "память",
        title: "Истории места",
        image: "../assets/site-images-v1/immersion/udege-youth-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/udege-youth-480.webp 480w, ../assets/site-images-v1/immersion/udege-youth-960.webp 960w, ../assets/site-images-v1/immersion/udege-youth-1254.webp 1254w",
        text: "Устные рассказы, топонимы и семейные истории помогают удерживать связь с конкретными реками и участками тайги. Без этой точности культура быстро превращается в абстракцию.",
        details: ["топонимы", "фольклор", "семейные истории"],
      },
    ],
    timeline: ["Тайга", "Реки Хор и Анюй", "Ремесла и знания о природе"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Какая пара лучше всего раскрывает удэгейскую тему на сайте?",
      options: ["Сихотэ-Алинь, реки Хор и Анюй", "Командоры, остров Беринга и алеутский язык", "Колыма, Индигирка и юкагирские языки"],
      answer: "Сихотэ-Алинь, реки Хор и Анюй",
    },
  },
  {
    slug: "negidal",
    name: "Негидальцы",
    image: "../assets/site-images-v1/people/negidal-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/negidal-320.webp 320w, ../assets/site-images-v1/people/negidal-512.webp 512w, ../assets/site-images-v1/people/negidal-768.webp 768w, ../assets/site-images-v1/people/negidal-1024.webp 1024w",
    titleMax: 78,
    population: "483 человека в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Амгунь и северное Приамурье",
    area: "taiga",
    areaLabel: "Тайга",
    language: "негидальский язык · тунгусо-маньчжурская семья",
    focus: "охота, рыболовство, речные поселения",
    summary:
      "Негидальцы - очень малочисленный народ бассейна Амгуни и нижнего Приамурья. В культуре важны речные поселения, охота, рыболовство, различие верховских и низовских групп, близость языка к эвенкийскому и особая хрупкость языковой памяти.",
    lead:
      "Негидальская тема требует особой точности: малочисленность народа делает язык, семейные истории и локальную память особенно хрупкими.",
    facts: ["бассейн Амгуни", "малочисленный народ", "речная культура"],
    sections: [
      ["Территория", "Негидальцы связаны с бассейном реки Амгунь и нижним Приамурьем. Важно различать верховские и низовские группы: их уклад и языковые особенности не полностью совпадали."],
      ["Язык", "Негидальский язык относится к тунгусо-маньчжурским языкам и близок к эвенкийскому. Современные данные показывают, что число активных носителей крайне мало."],
      ["Культура", "У низовских групп значимы рыболовство и оседлые поселения у воды; у верховских - охота, перемещения и связь с оленеводческими практиками."],
    ],
    immersion: [
      {
        kicker: "Амгунь",
        title: "Люди реки",
        image: "../assets/site-images-v1/immersion/negidal-river-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/negidal-river-480.webp 480w, ../assets/site-images-v1/immersion/negidal-river-960.webp 960w, ../assets/site-images-v1/immersion/negidal-river-1254.webp 1254w",
        text: "Само описание негидальской культуры начинается с Амгуни. Река определяла поселения, промысел, маршруты и локальную память, поэтому на странице она становится главным смысловым ориентиром.",
        details: ["Амгунь", "нижнее Приамурье", "береговые поселения"],
      },
      {
        kicker: "различие",
        title: "Верховские и низовские группы",
        image: "../assets/site-images-v1/immersion/negidal-groups-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/negidal-groups-480.webp 480w, ../assets/site-images-v1/immersion/negidal-groups-960.webp 960w, ../assets/site-images-v1/immersion/negidal-groups-1254.webp 1254w",
        text: "Исторически выделяли верховских и низовских негидальцев. Одни больше связаны с охотой и мобильностью, другие - с рыболовством и оседлой речной жизнью.",
        details: ["охота", "рыболовство", "локальные различия"],
      },
      {
        kicker: "язык",
        title: "Очень тонкая нить",
        image: "../assets/site-images-v1/immersion/negidal-language-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/negidal-language-480.webp 480w, ../assets/site-images-v1/immersion/negidal-language-960.webp 960w, ../assets/site-images-v1/immersion/negidal-language-1254.webp 1254w",
        text: "Негидальский язык - одна из самых уязвимых тем проекта. Здесь особенно важны записи слов, буквари, семейные воспоминания и работа с представителями сообщества.",
        details: ["букварь", "полевые записи", "семейная память"],
      },
    ],
    timeline: ["Амгунь", "Речной уклад", "Хрупкость языковой памяти"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Какой нюанс важен при описании негидальцев?",
      options: ["Различие верховских и низовских групп в бассейне Амгуни", "Разделение на островных и материковых алеутов", "Связь с юпикскими языками Берингова пролива"],
      answer: "Различие верховских и низовских групп в бассейне Амгуни",
    },
  },
  {
    slug: "evenki",
    name: "Эвенки",
    image: "../assets/site-images-v1/people/evenki-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/evenki-320.webp 320w, ../assets/site-images-v1/people/evenki-512.webp 512w, ../assets/site-images-v1/people/evenki-768.webp 768w, ../assets/site-images-v1/people/evenki-1024.webp 1024w",
    titleMax: 118,
    population: "39 420 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Таежный север ДВ",
    area: "north",
    areaLabel: "Север",
    language: "эвенкийский язык · тунгусо-маньчжурская семья",
    focus: "оленеводство, охота, кочевые маршруты",
    summary:
      "Эвенки расселены во многих регионах Сибири и Дальнего Востока, включая Хабаровский край. В краевом контексте особенно важны северная тайга, охота, оленеводство, маршруты, переносное жилище и экологическое восприятие природы как живого пространства.",
    lead:
      "Эвенкийская культура помогает говорить о северной мобильности, маршрутах, оленеводстве, охоте и знаниях о тайге.",
    facts: ["северные районы", "оленеводство", "кочевые практики"],
    sections: [
      ["Территория", "Эвенки живут на огромной территории России. Для Хабаровского края важны северные и таежные районы, где маршруты, промысел и сезонность задавали образ жизни."],
      ["Язык", "Эвенкийский язык входит в тунгусо-маньчжурскую семью и имеет несколько диалектных групп. Топонимы, песни, рассказы и названия предметов помогают сохранять живое присутствие языка."],
      ["Культура", "Охота, оленеводство, переносные жилища, лыжи, нарты, одежда из шкур и экологическая этика составляют важные темы эвенкийской страницы."],
    ],
    immersion: [
      {
        kicker: "маршрут",
        title: "Культура движения",
        image: "../assets/site-images-v1/immersion/evenki-route-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evenki-route-480.webp 480w, ../assets/site-images-v1/immersion/evenki-route-960.webp 960w, ../assets/site-images-v1/immersion/evenki-route-1254.webp 1254w",
        text: "Для эвенков движение по тайге - это не хаос, а точная карта сезонных путей. Маршрут связывает семью, стадо, охоту, погоду и память о местах.",
        details: ["сезонные переходы", "кочевье", "стойбища"],
      },
      {
        kicker: "олень",
        title: "Оленеводство и охота",
        image: "../assets/site-images-v1/immersion/evenki-reindeer-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evenki-reindeer-480.webp 480w, ../assets/site-images-v1/immersion/evenki-reindeer-960.webp 960w, ../assets/site-images-v1/immersion/evenki-reindeer-1254.webp 1254w",
        text: "Олень в эвенкийской культуре связан с транспортом, хозяйством и образом жизни. Охота при этом остается ключевым знанием о тайге и поведении животных.",
        details: ["олень", "лось", "промысловые знания"],
      },
      {
        kicker: "мир",
        title: "Природа как живое единство",
        image: "../assets/site-images-v1/immersion/evenki-nature-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evenki-nature-480.webp 480w, ../assets/site-images-v1/immersion/evenki-nature-960.webp 960w, ../assets/site-images-v1/immersion/evenki-nature-1254.webp 1254w",
        text: "В эвенкийской традиции человек мыслится частью природного мира. Поэтому образовательная подача должна быть не только о предметах, но и об отношении к месту.",
        details: ["экологическое знание", "уважение к природе", "устные рассказы"],
      },
    ],
    timeline: ["Северная тайга", "Оленеводство", "Маршруты и современность"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Какой признак лучше всего раскрывает эвенкийскую культуру движения?",
      options: ["Сезонные маршруты, охота и оленеводство северной тайги", "Оседлые поселения Нижнего Амура и речные лодки", "Островной промысел Командорских островов"],
      answer: "Сезонные маршруты, охота и оленеводство северной тайги",
    },
  },
  {
    slug: "evens",
    name: "Эвены",
    image: "../assets/site-images-v1/people/evens-1024.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/people/evens-320.webp 320w, ../assets/site-images-v1/people/evens-512.webp 512w, ../assets/site-images-v1/people/evens-768.webp 768w, ../assets/site-images-v1/people/evens-1024.webp 1024w",
    titleMax: 118,
    population: "19 975 человек в РФ по ВПН-2020 (проведена в 2021 году)",
    region: "Охотское побережье и север",
    area: "north",
    areaLabel: "Север",
    language: "эвенский язык · тунгусо-маньчжурская семья",
    focus: "оленеводство, северные маршруты, побережье",
    summary:
      "Эвены связаны с северными территориями, Охотским побережьем, оленеводством, охотой, рыболовством и сезонными переходами. В Хабаровском крае эвенская тема помогает говорить о побережье Охотского моря, мобильности и северной культуре маршрута.",
    lead:
      "Эвенская страница соединяет северные маршруты, оленеводство и побережье Охотского моря. Важно показать движение, сезонность и связь с местом.",
    facts: ["Охотское море", "северные маршруты", "оленеводство"],
    sections: [
      ["Территория", "В Хабаровском крае эвенская тема связана с севером и Охотским побережьем. Здесь важны маршруты между горно-таежными, промежуточными и приморскими зонами."],
      ["Язык", "Эвенский язык относится к тунгусо-маньчжурской семье и имеет несколько наречий. В образовательной подаче важно показывать язык через песни, имена мест и живые слова культуры."],
      ["Культура", "Кочевое оленеводство, охота, рыболовство, легкие временные жилища, одежда из шкур и бисерный орнамент связаны с сезонным циклом северной жизни."],
    ],
    immersion: [
      {
        kicker: "север",
        title: "Сезон как маршрут",
        image: "../assets/site-images-v1/immersion/evens-season-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evens-season-480.webp 480w, ../assets/site-images-v1/immersion/evens-season-960.webp 960w, ../assets/site-images-v1/immersion/evens-season-1254.webp 1254w",
        text: "Эвенский хозяйственный год строился вокруг переходов, промысла, погоды и состояния оленьего стада. Поэтому страница должна ощущаться как движение по северному календарю.",
        details: ["сезонность", "стойбища", "переходы"],
      },
      {
        kicker: "побережье",
        title: "Охотское море рядом",
        image: "../assets/site-images-v1/immersion/evens-coast-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evens-coast-480.webp 480w, ../assets/site-images-v1/immersion/evens-coast-960.webp 960w, ../assets/site-images-v1/immersion/evens-coast-1254.webp 1254w",
        text: "Для части эвенских групп важна связь с побережьем: рыба, морская среда и обмен с соседними народами дополняли оленеводческие и охотничьи практики.",
        details: ["Охотское побережье", "рыболовство", "приморская зона"],
      },
      {
        kicker: "узор",
        title: "Одежда, бисер, защита",
        image: "../assets/site-images-v1/immersion/evens-ornament-1254.webp",
        imageWidth: 1254, imageHeight: 1254,
        imageSrcset: "../assets/site-images-v1/immersion/evens-ornament-480.webp 480w, ../assets/site-images-v1/immersion/evens-ornament-960.webp 960w, ../assets/site-images-v1/immersion/evens-ornament-1254.webp 1254w",
        text: "Орнамент на одежде располагался по краям и швам, подчеркивал форму вещи и нес смысл защиты. Это хороший визуальный ключ для молодежной образовательной подачи.",
        details: ["бисер", "шкуры", "геометрический орнамент"],
      },
    ],
    timeline: ["Охотское побережье", "Северные маршруты", "Оленеводство и язык"],
    sourceLinks: [
      ["Единый перечень КМН РФ", "https://www.consultant.ru/document/cons_doc_LAW_26631/"],
      ["Численность по ВПН-2020", "https://raipon.info/press-tsentr/novosti/rezultaty-vserossiyskoy-perepisi-naseleniya-2020-po-natsionalnomu-sostavu-sredi-korennykh-malochisle/"],
      ["Справочник по народам", "https://arhiiv.eki.ee/books/redbook/index1.shtml"],
    ],
    quiz: {
      question: "Что точнее всего связывает эвенскую страницу с Охотским побережьем?",
      options: ["Оленеводство, северные маршруты и приморская зона", "Амурский лиман, язык-изолят и сахалинские группы", "Уссурийская тайга, земледелие и тазская история"],
      answer: "Оленеводство, северные маршруты и приморская зона",
    },
  },
];
